### ISSUE TITLE
Not a complete dhclient, and code style too ugly

### ISSUE THREAD

**Issue by tidatida** [saravana815/dhtest#18]
It can't set interface ip/ mask / route / dns , it only printf out received info. And the code use SO MANY  GLOBAL PARAMATERS ... ... 

Maybe I will delete all above, but I can't  hide my disappointment now.

**Comment by saravana815** [comment]
Hi, 
The very purpose of this tool is to simulate multiple dhcp clients behind switch, router, etc. 

This tool is not intended to modify the IP stack of linux machine. The code is quite/very old and no intentions to rework the code. 

If you want something new, please start separate project on github and use dhtest reusable code if you want. I would suggest you to start new dhclient based on python for both ipv4 and ipv6 and this is my suggestion and it is upto you.

Let this tool be as it is since it solves the problem for which it is meant. 

Regards,
Saravana
