### ISSUE TITLE
vlan option doesn't work

### ISSUE THREAD

**Issue by biggena** [saravana815/dhtest#27]
vlan option (-v) doesn't work, I see in wireshark tagged DHCP Discovers and Offers, but dhtest doesn't recognize Offers at all and keeps sending Discover.
Tried on dhtest version 1.5, also on 1.1, the same behavior.
ubuntu@ubuntu:~/dhtest-master$ sudo ./dhtest -m 00:00:00:11:11:11 -i ens3 -v 300
DHCP discover sent       - Client MAC : 00:00:00:11:11:11
DHCP discover sent       - Client MAC : 00:00:00:11:11:11
DHCP discover sent       - Client MAC : 00:00:00:11:11:11
DHCP discover sent       - Client MAC : 00:00:00:11:11:11
DHCP discover sent       - Client MAC : 00:00:00:11:11:11

![image](https://user-images.githubusercontent.com/40003342/71128205-60070b80-21f5-11ea-832f-6cf3709c5461.png)

**Comment by saravana815** [comment]
Hi, for a very long time, i just run the tool in my laptop setup which does not have any vlan support.  So checking for the issue which you mentioned is difficult due to setup limitation. 
As workaround why dont enable vlan interface on linux and run the dhtest on top of vlan interface - https://www.slashroot.in/vlan-configuration-linux-nic-interface
